import React, { useState } from 'react';
import { X, Share2, Copy, Check, Download, FileText, Globe } from 'lucide-react';
import { motion } from 'motion/react';
import { ChatMessage } from '../../types/chat';

interface ShareModalProps {
  isOpen: boolean;
  onClose: () => void;
  conversationTitle?: string;
  messages: ChatMessage[];
}

export const ShareModal: React.FC<ShareModalProps> = ({
  isOpen,
  onClose,
  conversationTitle = 'DOTVEX 2.0 Conversation',
  messages,
}) => {
  const [copiedLink, setCopiedLink] = useState(false);
  const [copiedMarkdown, setCopiedMarkdown] = useState(false);

  if (!isOpen) return null;

  const shareUrl = window.location.href;

  const handleCopyLink = () => {
    navigator.clipboard.writeText(shareUrl);
    setCopiedLink(true);
    setTimeout(() => setCopiedLink(false), 2000);
  };

  const getMarkdownTranscript = () => {
    return `# ${conversationTitle}\n*Generated by DOTVEX 2.0 (Dotman / Olalemi Michael Adedotun)*\n\n` +
      messages
        .map((m) => `### ${m.role === 'user' ? 'User' : 'DOTVEX 2.0'}\n${m.content}\n`)
        .join('\n---\n\n');
  };

  const handleCopyMarkdown = () => {
    navigator.clipboard.writeText(getMarkdownTranscript());
    setCopiedMarkdown(true);
    setTimeout(() => setCopiedMarkdown(false), 2000);
  };

  const handleDownloadMarkdown = () => {
    const md = getMarkdownTranscript();
    const blob = new Blob([md], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${conversationTitle.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.md`;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/75 backdrop-blur-xs animate-fadeIn">
      <div className="absolute inset-0" onClick={onClose} />
      <motion.div
        initial={{ opacity: 0, scale: 0.96 }}
        animate={{ opacity: 1, scale: 1 }}
        className="relative w-full max-w-lg rounded-2xl bg-[#212121] border border-[#333] shadow-2xl overflow-hidden flex flex-col text-[#ececec]"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between px-5 py-4 border-b border-[#333]">
          <div className="flex items-center gap-2.5">
            <div className="p-2 rounded-xl bg-[#2f2f2f] text-blue-400">
              <Share2 className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-base font-semibold">Share Conversation</h2>
              <p className="text-xs text-[#b4b4b4]">Export transcript or create a public reference link</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg text-[#8e8e8e] hover:text-[#ececec] hover:bg-[#2f2f2f] transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content */}
        <div className="p-5 space-y-4">
          <div className="p-4 rounded-xl bg-[#2a2a2a] border border-[#383838] space-y-2">
            <div className="text-xs font-medium text-[#b4b4b4]">Conversation Link</div>
            <div className="flex items-center gap-2">
              <input
                type="text"
                readOnly
                value={shareUrl}
                className="flex-1 px-3 py-2 rounded-lg bg-[#1a1a1a] border border-[#333] text-xs text-[#ececec] font-mono focus:outline-none"
              />
              <button
                onClick={handleCopyLink}
                className="px-3.5 py-2 rounded-lg bg-emerald-600 hover:bg-emerald-500 text-xs font-semibold text-white flex items-center gap-1.5"
              >
                {copiedLink ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                <span>{copiedLink ? 'Copied' : 'Copy'}</span>
              </button>
            </div>
          </div>

          <div className="grid grid-cols-2 gap-3">
            <button
              onClick={handleCopyMarkdown}
              className="p-3 rounded-xl bg-[#2a2a2a] hover:bg-[#333] border border-[#383838] text-left space-y-1 transition-all"
            >
              <div className="flex items-center gap-2 text-xs font-medium text-[#ececec]">
                <FileText className="w-4 h-4 text-cyan-400" />
                <span>Copy as Markdown</span>
              </div>
              <p className="text-[11px] text-[#8e8e8e]">Copy formatted markdown with reasoning steps</p>
            </button>

            <button
              onClick={handleDownloadMarkdown}
              className="p-3 rounded-xl bg-[#2a2a2a] hover:bg-[#333] border border-[#383838] text-left space-y-1 transition-all"
            >
              <div className="flex items-center gap-2 text-xs font-medium text-[#ececec]">
                <Download className="w-4 h-4 text-emerald-400" />
                <span>Download .MD</span>
              </div>
              <p className="text-[11px] text-[#8e8e8e]">Save transcript file to your local computer</p>
            </button>
          </div>
        </div>
      </motion.div>
    </div>
  );
};
